export const LOGIN = 'LOGIN';
export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PHARMACISTS = 'FETCH_PHARMACISTS';
export const FETCH_STAFF_MEMBERS = 'FETCH_STAFF_MEMBERS';
